import {
  BabyIcon,
  BanknoteIcon,
  BeerIcon,
  BikeIcon,
  BookIcon,
  BriefcaseIcon,
  BusIcon,
  CarIcon,
  CatIcon,
  CoffeeIcon,
  CoinsIcon,
  CreditCardIcon,
  DogIcon,
  DropletsIcon,
  DumbbellIcon,
  EllipsisIcon,
  FilmIcon,
  FlameIcon,
  FuelIcon,
  Gamepad2Icon,
  GiftIcon,
  GlassesIcon,
  GraduationCapIcon,
  HammerIcon,
  HandCoinsIcon,
  HeartIcon,
  HouseIcon,
  KeyIcon,
  LandmarkIcon,
  LaptopIcon,
  MusicIcon,
  PaletteIcon,
  PawPrintIcon,
  PiggyBankIcon,
  PillIcon,
  PizzaIcon,
  PlaneIcon,
  ReceiptIcon,
  ScissorsIcon,
  ShieldIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SparklesIcon,
  StethoscopeIcon,
  TicketIcon,
  TrainFrontIcon,
  TreePalmIcon,
  TrendingUpIcon,
  TvIcon,
  UsersIcon,
  UtensilsIcon,
  WifiIcon,
  WrenchIcon,
  ZapIcon,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icons a category can have, by the name stored in categories.icon. The first names are the ones
 * the starter templates use (some predate lucide, hence "bolt", "home", "dots-horizontal"); the
 * rest widen the choice. Order is the order of the picker.
 */
export const CATEGORY_ICONS: Readonly<Record<string, LucideIcon>> = {
  'shopping-cart': ShoppingCartIcon,
  coffee: CoffeeIcon,
  car: CarIcon,
  home: HouseIcon,
  bolt: ZapIcon,
  heart: HeartIcon,
  film: FilmIcon,
  book: BookIcon,
  bag: ShoppingBagIcon,
  key: KeyIcon,
  briefcase: BriefcaseIcon,
  laptop: LaptopIcon,
  gift: GiftIcon,
  'trending-up': TrendingUpIcon,
  utensils: UtensilsIcon,
  pizza: PizzaIcon,
  beer: BeerIcon,
  shirt: ShirtIcon,
  glasses: GlassesIcon,
  scissors: ScissorsIcon,
  sparkles: SparklesIcon,
  bus: BusIcon,
  train: TrainFrontIcon,
  fuel: FuelIcon,
  bike: BikeIcon,
  plane: PlaneIcon,
  'tree-palm': TreePalmIcon,
  ticket: TicketIcon,
  gamepad: Gamepad2Icon,
  music: MusicIcon,
  palette: PaletteIcon,
  tv: TvIcon,
  smartphone: SmartphoneIcon,
  wifi: WifiIcon,
  droplets: DropletsIcon,
  flame: FlameIcon,
  wrench: WrenchIcon,
  hammer: HammerIcon,
  pill: PillIcon,
  stethoscope: StethoscopeIcon,
  dumbbell: DumbbellIcon,
  shield: ShieldIcon,
  'graduation-cap': GraduationCapIcon,
  baby: BabyIcon,
  users: UsersIcon,
  'paw-print': PawPrintIcon,
  dog: DogIcon,
  cat: CatIcon,
  receipt: ReceiptIcon,
  'credit-card': CreditCardIcon,
  landmark: LandmarkIcon,
  banknote: BanknoteIcon,
  coins: CoinsIcon,
  'hand-coins': HandCoinsIcon,
  'piggy-bank': PiggyBankIcon,
  'dots-horizontal': EllipsisIcon,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

/** Colors a category can have: the starter templates' Material palette, plus a few to fill gaps. */
export const CATEGORY_COLORS = [
  '#F44336',
  '#E91E63',
  '#9C27B0',
  '#673AB7',
  '#3F51B5',
  '#2196F3',
  '#00BCD4',
  '#009688',
  '#4CAF50',
  '#8BC34A',
  '#FFC107',
  '#FF9800',
  '#FF5722',
  '#795548',
  '#607D8B',
  '#9E9E9E',
] as const;

const HEX_COLOR = /^#[0-9a-f]{6}$/i;

/** The color to render, or null for one that isn't a plain #RRGGBB (and so can't be tinted). */
export function categoryColor(color: string | null | undefined): string | null {
  return color && HEX_COLOR.test(color) ? color : null;
}

/** A suggestion for a new category: its parent's look, or the next palette color for a top level one. */
export function defaultAppearance(
  parent: { icon: string | null; color: string | null } | undefined,
  siblingCount: number,
): { icon: string | null; color: string } {
  return {
    icon: parent?.icon ?? null,
    color: categoryColor(parent?.color) ?? CATEGORY_COLORS[siblingCount % CATEGORY_COLORS.length],
  };
}
