import { CategoryType } from '@ft/api-database';

export interface CategoryTemplate {
  key: string;
  sortOrder: number;
  name: string;
  icon: string;
  color: string;
  type: CategoryType;
  lang: string;
}

// Mirrors the category_templates rows from
// `migrations/02 - Seed currencies, templates for categories and accounts.sql` — kept as code,
// not a DB table (see local/plans/02-development-plan.md, phase 5 decision).
export const CATEGORY_TEMPLATES: readonly CategoryTemplate[] = [
  // income
  {
    key: 'salary',
    sortOrder: 1,
    name: 'Salary',
    icon: 'briefcase',
    color: '#4CAF50',
    type: CategoryType.INCOME,
    lang: 'en',
  },
  {
    key: 'salary',
    sortOrder: 1,
    name: 'Зарплата',
    icon: 'briefcase',
    color: '#4CAF50',
    type: CategoryType.INCOME,
    lang: 'ru',
  },
  {
    key: 'freelance',
    sortOrder: 2,
    name: 'Freelance',
    icon: 'laptop',
    color: '#2196F3',
    type: CategoryType.INCOME,
    lang: 'en',
  },
  {
    key: 'freelance',
    sortOrder: 2,
    name: 'Фриланс',
    icon: 'laptop',
    color: '#2196F3',
    type: CategoryType.INCOME,
    lang: 'ru',
  },
  { key: 'gift', sortOrder: 3, name: 'Gift', icon: 'gift', color: '#E91E63', type: CategoryType.INCOME, lang: 'en' },
  {
    key: 'gift',
    sortOrder: 3,
    name: 'Подарок',
    icon: 'gift',
    color: '#E91E63',
    type: CategoryType.INCOME,
    lang: 'ru',
  },
  {
    key: 'investment',
    sortOrder: 4,
    name: 'Investment',
    icon: 'trending-up',
    color: '#FF9800',
    type: CategoryType.INCOME,
    lang: 'en',
  },
  {
    key: 'investment',
    sortOrder: 4,
    name: 'Инвестиции',
    icon: 'trending-up',
    color: '#FF9800',
    type: CategoryType.INCOME,
    lang: 'ru',
  },
  {
    key: 'other_income',
    sortOrder: 999,
    name: 'Other',
    icon: 'dots-horizontal',
    color: '#9E9E9E',
    type: CategoryType.INCOME,
    lang: 'en',
  },
  {
    key: 'other_income',
    sortOrder: 999,
    name: 'Прочее',
    icon: 'dots-horizontal',
    color: '#9E9E9E',
    type: CategoryType.INCOME,
    lang: 'ru',
  },
  // expense
  {
    key: 'groceries',
    sortOrder: 1,
    name: 'Groceries',
    icon: 'shopping-cart',
    color: '#4CAF50',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'groceries',
    sortOrder: 1,
    name: 'Продукты',
    icon: 'shopping-cart',
    color: '#4CAF50',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'transport',
    sortOrder: 2,
    name: 'Transport',
    icon: 'car',
    color: '#2196F3',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'transport',
    sortOrder: 2,
    name: 'Транспорт',
    icon: 'car',
    color: '#2196F3',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'housing',
    sortOrder: 3,
    name: 'Housing',
    icon: 'home',
    color: '#FF9800',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'housing',
    sortOrder: 3,
    name: 'Жильё',
    icon: 'home',
    color: '#FF9800',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'utilities',
    sortOrder: 4,
    name: 'Utilities',
    icon: 'bolt',
    color: '#FFC107',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'utilities',
    sortOrder: 4,
    name: 'Коммунальные услуги',
    icon: 'bolt',
    color: '#FFC107',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'health',
    sortOrder: 5,
    name: 'Health',
    icon: 'heart',
    color: '#E91E63',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'health',
    sortOrder: 5,
    name: 'Здоровье',
    icon: 'heart',
    color: '#E91E63',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'entertainment',
    sortOrder: 6,
    name: 'Entertainment',
    icon: 'film',
    color: '#9C27B0',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'entertainment',
    sortOrder: 6,
    name: 'Развлечения',
    icon: 'film',
    color: '#9C27B0',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'dining_out',
    sortOrder: 7,
    name: 'Dining Out',
    icon: 'coffee',
    color: '#795548',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'dining_out',
    sortOrder: 7,
    name: 'Кафе и рестораны',
    icon: 'coffee',
    color: '#795548',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'shopping',
    sortOrder: 8,
    name: 'Shopping',
    icon: 'bag',
    color: '#607D8B',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'shopping',
    sortOrder: 8,
    name: 'Покупки',
    icon: 'bag',
    color: '#607D8B',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'education',
    sortOrder: 9,
    name: 'Education',
    icon: 'book',
    color: '#3F51B5',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'education',
    sortOrder: 9,
    name: 'Образование',
    icon: 'book',
    color: '#3F51B5',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  { key: 'rent', sortOrder: 10, name: 'Rent', icon: 'key', color: '#8BC34A', type: CategoryType.EXPENSE, lang: 'en' },
  {
    key: 'rent',
    sortOrder: 10,
    name: 'Аренда',
    icon: 'key',
    color: '#8BC34A',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
  {
    key: 'other_expense',
    sortOrder: 999,
    name: 'Other',
    icon: 'dots-horizontal',
    color: '#9E9E9E',
    type: CategoryType.EXPENSE,
    lang: 'en',
  },
  {
    key: 'other_expense',
    sortOrder: 999,
    name: 'Прочее',
    icon: 'dots-horizontal',
    color: '#9E9E9E',
    type: CategoryType.EXPENSE,
    lang: 'ru',
  },
];
